### PR TITLE
change Env type to unknown to conform @cloudflare/workers-types

### PR DESCRIPTION
**Pull request by kidylee**
``` typescript
declare type ExportedHandlerFetchHandler<Env = unknown> = (
  request: Request,
  env: Env,
  ctx: ExecutionContext
) => Response | Promise<Response>;
```

By using unknown, developer could define binding types by themselives.

``` typescript
interface Bindings {
  TWITTER_BEARER: string;
  TWITTER_ACCOUNT: string;

  CONSUMER_KEY: string;
  CONSUMER_SECRET: string;
  ACCESS_TOKEN_KEY: string;
  ACCESS_TOKEN_SECRET: string;
}
```
``` typescript
export const worker = {
  async fetch(
    request: Request,
    env: Bindings,
    ctx: ExecutionContext
  ): Promise<Response> {
    return router.handle(request, env, ctx);
  },
};
```

### CODE REVIEW

**Comment by markusahlstrand** [comment]
Hi @kidylee !

I would have expected this to work as well as this should be covered by `{[key: string]: string}` right?

The idea was that you can create your typed router like this:
```
const router = new Router<Binding>()
```

This way your bindings will be typed which is pretty nice. 

What's your thoughts on this?

**Comment by kidylee** [comment]
Ha, I see. I'm using the wrong way of generic.

In this case, I would like add Fetcher into the generic type, which represents service binding:

https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/

```
export class Router<Env = { [key: string]: string | DurableObjectNamespace | KVNamespace | Fetcher}>
```

**Comment by kidylee** [comment]
I have added Fetcher support and improved jest setup in project.

**Comment by markusahlstrand** [comment]
Looks great!

**Pull request merged**
