### PR TITLE
Use standard DELETE method name

### PR DESCRIPTION
**Pull request by MiroslavPetrik**
I was wondering why my DELETE requests were failing...

### CODE REVIEW

**Comment by markusahlstrand** [comment]
HI @MiroslavPetrik and thanks for the PR!

Had a check on how koa-router named the functions and it actually seems that they support both (https://github.com/ZijianHe/koa-router#module_koa-router--Router+get%7Cput%7Cpost%7Cpatch%7Cdelete%7Cdel). I previously used del rather than delete as it's a reserved word in javascript (https://www.w3schools.com/js/js_reserved.asp), but think both should work just fine.

I'm considering if the best solution would be to go down the same route as koa-router and support both? That way it's not a breaking change which is always nice. Does this sound like a good solution to you? If so would you rather update the PR or should I do the changes in a PR on my side and push it?

Thanks!

**Comment by markusahlstrand** [comment]
Realized now what the issue is ;) As the verb in the constants is DEL rather than DELETE it won't match in the resolver.. There are a few more references that needs to be updated, so I'll go ahead and post a fix for it. Thanks!!

**Comment by markusahlstrand** [comment]
Pushed an update containing this fix now. Thanks for helping out!

**Comment by MiroslavPetrik** [comment]
❤

**Pull request closed without merging**
